### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error en Filtro]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#1]
Filtro de Actividades, cuando se filtrar por cualquier campo y luego se presiona "Limpiar"  no trae todas las actividades.

![filtro](https://cloud.githubusercontent.com/assets/25032866/21807878/84b302aa-d71f-11e6-8760-1f343b6b7be4.png)

**Comment by ppereznetred** [comment]
corregido en preproducción

**Comment by PamelaGonzalezR** [comment]
Se ejecuta la prueba con éxito.
