### ISSUE TITLE
[sprint 3] [Perfiles] [Nombre botón Exportar]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#10]
El nombre del botón "Exportar perfil" esta mal escrito. Favor m.odificar

![exp](https://cloud.githubusercontent.com/assets/25032866/22072201/57282c04-dd80-11e6-9b73-b7bf64d509cd.png)

**Comment by Oscar-Rivera** [comment]
Se soluciona problema con nombre de Botón.
