### ISSUE TITLE
[Sprint 6][Actividades][Problemas con el archivo excel descargado] 

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#14]
Nombre del archivo excel no corresponde. Favor cambiar

![descarga](https://cloud.githubusercontent.com/assets/25032866/22211538/1221708a-e16c-11e6-8514-543db05e6b7f.png)

**Comment by Oscar-Rivera** [comment]
se cambia el nombre y también se soluciona problema con las columnas.
