### ISSUE TITLE
[Sprint 6][Actividades][Problemas con el archivo excel descargado]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#15]
Archivo excel, viene con campos Nulos y No Objet. Favor validar

![excel](https://cloud.githubusercontent.com/assets/25032866/22211610/588375c8-e16c-11e6-8f7f-0dfae1e5ed2b.png)

**Comment by Oscar-Rivera** [comment]
Se resuelve problema.
