### ISSUE TITLE
[Sprint 7][Actividad "Evento de Inicio" no guarda % Avance]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#16]
Al crear la actividad por primera vez guarda el dato, pero al editar el dato ya no aparece y se debe volver a ingresar.

![porcent](https://cloud.githubusercontent.com/assets/25032866/22435176/cc31071a-e6fd-11e6-8b53-3a89ca1aa6d1.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se valida correción.
