### ISSUE TITLE
[Sprint 7][Columna % Avance]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#18]
La columna "% Avance" viene sin datos en todos los detalles, al pinchar cada link.

![image](https://cloud.githubusercontent.com/assets/25032866/22492585/4bbf36da-e809-11e6-9dde-621a80ceb032.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Aprobado.
