### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error en Imagenes] 

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#2]
Al ingresar la URL de una imagen y querer mostrarla, esta no se carga bien.

![imagenes](https://cloud.githubusercontent.com/assets/25032866/21810668/7b7e5a52-d72b-11e6-8bca-809c65f44b38.png)

**Comment by ppereznetred** [comment]
no aplica ya que la prueba no se realizó correctamente

**Comment by PamelaGonzalezR** [comment]
La carga de las imágenes corresponde a la URL de la imagen, no de la fuente de donde se saca, por ejemplo google.
