### ISSUE TITLE
[Sprint 7][Dashboard 1][Excel Gestión Anual Historica]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#21]
No trae datos el excel, al momento de descargarlo.

![image](https://cloud.githubusercontent.com/assets/25032866/22512634/7705d956-e878-11e6-9e01-335bf0cc77f1.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se valida funcionalidad.
