### ISSUE TITLE
[Sprint 7][Dashboard 2][Diseño botones]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#23]
Favor cambiar el diseño de los botones del filtro. Se debe mantener el diseño del menú administración.

Dashboard 2:
![image](https://cloud.githubusercontent.com/assets/25032866/22553238/c23dd58c-e93a-11e6-9f4a-ac5467f7b08e.png)

administración:

![image](https://cloud.githubusercontent.com/assets/25032866/22553263/dd25f46a-e93a-11e6-9328-e402221fed95.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se valida corrección.
