### ISSUE TITLE
[Sprint 7][Dashboard 2][Nombre Mes]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#24]
Favor poner mes correspondiente, en vez de número.

![image](https://cloud.githubusercontent.com/assets/25032866/22553856/eb7f32f4-e93c-11e6-811e-a6d6490f39b4.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Validado
