### ISSUE TITLE
[Sprint 7][Dashboard 2][Botón Limpiar]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#25]
Al ingresar los siguientes filtros, y filtrar la funcionalidad hace lo correcto. 
Pero al presionar Limpiar, quedan los mismo datos en los gafricos y/u indicadores en el caso que corresponda, osea no limpia.

![image](https://cloud.githubusercontent.com/assets/25032866/22554296/5b9ab026-e93e-11e6-9de1-0b83e596bc64.png)

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Validado
