### ISSUE TITLE
[Sprint 7][Dashboard 3][Falta gráfico Tipos requerimientos anual]

### ISSUE THREAD

**Issue by Netred-Komatsu** [Netred-SA/komatsu_pgp#26]
No se visualiza gráfico.

![image](https://cloud.githubusercontent.com/assets/18294500/22561734/3f43ea5e-e958-11e6-85c5-230588b0531f.png)

Se sabe de esta información, pero por ejecución de pruebas se debe registrar.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Validado
