### ISSUE TITLE
[Sprint 7][Dashboard 3][PDF]

### ISSUE THREAD

**Issue by Netred-Komatsu** [Netred-SA/komatsu_pgp#27]
El archivo PDF que se descarga del dashboard 3, no carga los gráficos.

![image](https://cloud.githubusercontent.com/assets/18294500/22561917/2c0af580-e959-11e6-86e0-d71c47574e2a.png)

Se esta al tanto de esta modificación, pero como se comenzó con la ejecución de las pruebas, debo registrarla.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se valida corrección.
