### ISSUE TITLE
[Sprint 7][Dashboard 3][Botón Limpiar]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#28]
Al ingresar los siguientes filtros, y filtrar la funcionalidad hace lo correcto.
Pero al presionar Limpiar, quedan los mismo datos en los gráficos y/u indicadores en el caso que corresponda, osea no limpia. 

![image](https://cloud.githubusercontent.com/assets/25032866/22578574/75eb6dfc-e9a8-11e6-9857-ea28b0974447.png)

Esto ocurre con todos los campos, osea, proceso, empresa y componente.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Validado
