### ISSUE TITLE
[Sprint 7][Reporte Reporte Avance de Portafolios]

### ISSUE THREAD

**Issue by Netred-Komatsu** [Netred-SA/komatsu_pgp#29]
La palabra debe "Procesos Afectados" en el filtro.

![image](https://cloud.githubusercontent.com/assets/18294500/22827059/a19431d8-ef74-11e6-8f9e-50cadb6a29be.png)

favor, cambiar

**Comment by PamelaGonzalezR** [comment]
corregido.
