### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error Actividad Decisión]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#3]
Segun documento funcional, la actividad de decisión debe mostrar la siguiente información al momento de presionar "Ejecutar Actividad":

![actdecis](https://cloud.githubusercontent.com/assets/25032866/21812268/1b77e29e-d731-11e6-8fbd-e3eddf926bdc.png)

Favor modificar.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se ejecuta la prueba con éxito.
