### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error Actividad Tarea]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#4]
Según documento funcional, la actividad de tarea debe mostrar la siguiente información al momento de presionar "Ejecutar Actividad":

![acttarea](https://cloud.githubusercontent.com/assets/25032866/21812505/ed0afa58-d731-11e6-9827-7cbf7ec96ae4.png)

Favor agregar.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se ejecuta la prueba con éxito.
