### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error Actividad de Inicio]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#5]
Segun documento funcional, la actividad de inicio debe mostrar la siguiente información al momento de presionar "Ejecutar Actividad":

![actini](https://cloud.githubusercontent.com/assets/25032866/21812555/1f9275a0-d732-11e6-9b38-5f9d6c58132a.png)

Favor agregar.

**Comment by ppereznetred** [comment]
corregido

**Comment by PamelaGonzalezR** [comment]
Se ejecuta la prueba con éxito.
