### ISSUE TITLE
[Sprint 6] [Mis Actividades] [Error planilla RFC]

### ISSUE THREAD

**Issue by PamelaGonzalezR** [Netred-SA/komatsu_pgp#6]
Falta la opción de "Otros" en el campo "Componente(s) afectado(s)" .

![otros](https://cloud.githubusercontent.com/assets/25032866/21818332/22a995a2-d746-11e6-831e-35f4505b983b.png)

**Comment by ppereznetred** [comment]
corregido en preproducción

**Comment by PamelaGonzalezR** [comment]
Se valida corrección.
