### ISSUE TITLE
[Sprint 2] [Empresas] [Error en mensaje]

### ISSUE THREAD

**Issue by Netred-Komatsu** [Netred-SA/komatsu_pgp#8]
Favor cambiar parte del mensaje de validación en "creados" por "creadas".
Esto se da, al momento de filtrar y buscar una empresa que no existe.

![empresa](https://cloud.githubusercontent.com/assets/18294500/21989616/5c43b90c-dbea-11e6-8a5c-7dd8afab86d7.png)

**Comment by Oscar-Rivera** [comment]
Se soluciona problema con mensaje:

![image](https://cloud.githubusercontent.com/assets/25032414/22267133/66de6664-e261-11e6-9450-e7582c3e9bb0.png)
